# Maak first = "Hallo", name = "Janiek"
# Bouw message met een f-string zodat de output exact "Hallo, Janiek!" is
# Schrijf je code hieronder:
# first = ...
# name = ...
# message = ...
# print(message)
