# Maak text = "  spam, spam, eggs  "
# Verwijder spaties met strip(), vervang "spam, " zodat alleen "eggs" overblijft.
# Tip: vervang ALLE voorkomens.
# Schrijf je code hieronder:
# text = ...
# stripped = ...
# cleaned = ...
# print(cleaned)
